services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: white-game-backend-dev
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - /app/backend/node_modules
      - /app/shared/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=*
    networks:
      - white-game-network
    command: sh -c "cd /app/shared && npm install && cd /app/backend && npm install && npm run dev"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: white-game-frontend-dev
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
      - /app/frontend/node_modules
      - /app/shared/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - white-game-network
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_WS_URL=ws://localhost:3000
    command: sh -c "cd /app/shared && npm install && cd /app/frontend && npm install && npm run dev"

networks:
  white-game-network:
    driver: bridge